# Generated by Django 3.2.5 on 2021-08-07 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='email',
            new_name='subscription_emails',
        ),
    ]
